# Generated by Django 4.2.27 on 2026-01-07 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='ScoreConfiguration',
            fields=[
                ('metric_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'score_configurations',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_state', models.CharField(max_length=20)),
                ('complexity', models.CharField(max_length=20)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='workforce.employee')),
            ],
            options={
                'db_table': 'pull_requests',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('resolution_time_hours', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='workforce.employee')),
            ],
            options={
                'db_table': 'issues',
            },
        ),
        migrations.CreateModel(
            name='ImpactScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('impact_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('silent_architect', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='impact_scores', to='workforce.employee')),
            ],
            options={
                'db_table': 'impact_scores',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='workforce.team'),
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('complexity', models.CharField(max_length=20)),
                ('lines_changed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='workforce.employee')),
            ],
            options={
                'db_table': 'contributions',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workforce.employee')),
            ],
            options={
                'db_table': 'activities',
            },
        ),
    ]
