# Generated by Django 6.0.1 on 2026-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMetricConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('weights', models.JSONField(default=dict)),
                ('impact_threshold', models.IntegerField(default=65)),
                ('activity_threshold', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'team_metric_configurations',
            },
        ),
    ]
